# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GIDLaC
                                 A QGIS plugin
 This plugin aids in labelling data for Classification
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-08-15
        copyright            : (C) 2022 by Jeremy Graham MTRI
        email                : jeremyg@mtu.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GIDLaC class from file GIDLaC.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gidlac import GIDLaC
    return GIDLaC(iface)
