# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GIDLaCDockWidget
                                 A QGIS plugin
 This plugin aids in labelling data for Classification
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-08-15
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Jeremy Graham MTRI
        email                : jeremyg@mtu.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import QgsMapLayerProxyModel
from qgis.gui import QgsMapLayerComboBox

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Raster_Layer_popup.ui'))

class AddRasterLayer(QtWidgets.QDialog, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(AddRasterLayer, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    #     self.comboBox = QgsMapLayerComboBox(self)
    #     self.comboBox.setFilters(QgsMapLayerProxyModel.RasterLayer)
    #     self.buttonBox = QtWidgets.QDialogButtonBox(self)
    #
    #     self.signals_connection()
    #
    # def signals_connection(self):
    #     self.buttonBox.accepted.connect(self.returnLayer)
    #     self.buttonBox.rejected.connect(self.cancel)
    #
    # def returnLayer(self):
    #     print('clicked accept')
    #     currentfile = self.AddRasterLayer.comboFile.currentLayer()
    #     print(currentfile)

    # def cancel(self):
    #     print('canceled')
    #     self.close()

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()

